### PR TITLE
Had to revert a previously reverted merge to bring the tooltip positi…

### PR DESCRIPTION
**Pull request by md-jafuss**
…oning

updates

Revert "Merge pull request #32 from markitondemand/revert-31-feature/tooltip-position-updates"

This reverts commit 4e9579bb2847cc0c27deabe965bbe52b75a225f5, reversing
changes made to 5dc3c7ea59db90a6c4f819be84db4992dd49d71a.

Conflicts:
	dist/js/tooltip.min.js
	package.json

### CODE REVIEW

**Comment by md-jafuss** [comment]
not sure why my commit message got screwed up but this "reverts a revert", essentially bringing back in my changes from pull request #31.

**Comment by micha3ldavid** [comment]
@fusseneg @Fully34 Can we get a live example of this change? Maybe set up a code pen or something so we can see exactly the reason for this and/if there is a less complicated way of achieving the same result.

Thanks,
Michael

**Comment by md-jafuss** [comment]
Hey Michael,

I just got back into the office and have to prepare our project for a release but I will try to get an example demonstrating what wasn’t working and what it fixed whenever I get a chance.

Thanks,
- Jason

**Comment by md-jafuss** [comment]
Hey @micha3ldavid. lets hold off on this PR until I can get an example of why this change was necessary.
I will close it for now and reopen in when I have more details.

**Pull request closed without merging**
